### ISSUE TITLE
Some problems when run training

### ISSUE THREAD

**Issue by tranbaokhanh26** [robot-learning-freiburg/EfficientLPS#4]
Hello Abhinav Valada and Rohit Mohan. I have some problems when running your code.

missing keys in source state_dict: range_weight, conv_stem.weight

********************************************************************************
Cleaning point-clouds with kNN post-processing
kNN parameters:
knn: 5
search: 5
sigma: 3.0
cutoff: 1.0
nclasses: 19
********************************************************************************
Traceback (most recent call last):
  File "/media/khanh/khanh4/lidar_segmentation/EfficientLPS/tools/train.py", line 145, in <module>
    main()
  File "/media/khanh/khanh4/lidar_segmentation/EfficientLPS/tools/train.py", line 141, in main
    meta=meta)
  File "/media/khanh/khanh4/lidar_segmentation/EfficientLPS/mmdet/apis/train.py", line 102, in train_detector
    meta=meta)
  File "/media/khanh/khanh4/lidar_segmentation/EfficientLPS/mmdet/apis/train.py", line 139, in _dist_train
    find_unused_parameters=find_unused_parameters)
  File "/home/khanh/anaconda3/envs/efficientLPS_env/lib/python3.7/site-packages/torch/nn/parallel/distributed.py", line 410, in __init__
    self._sync_params_and_buffers(authoritative_rank=0)
  File "/home/khanh/anaconda3/envs/efficientLPS_env/lib/python3.7/site-packages/torch/nn/parallel/distributed.py", line 420, in _sync_params_and_buffers
    authoritative_rank)
  File "/home/khanh/anaconda3/envs/efficientLPS_env/lib/python3.7/site-packages/torch/nn/parallel/distributed.py", line 979, in _distributed_broadcast_coalesced
    self.process_group, tensors, buffer_size, authoritative_rank
RuntimeError: CUDA error: no kernel image is available for execution on the device
Traceback (most recent call last):
  File "/home/khanh/anaconda3/envs/efficientLPS_env/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/home/khanh/anaconda3/envs/efficientLPS_env/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/khanh/anaconda3/envs/efficientLPS_env/lib/python3.7/site-packages/torch/distributed/launch.py", line 260, in <module>
    main()
  File "/home/khanh/anaconda3/envs/efficientLPS_env/lib/python3.7/site-packages/torch/distributed/launch.py", line 256, in main
    cmd=cmd)
subprocess.CalledProcessError: Command '['/home/khanh/anaconda3/envs/efficientLPS_env/bin/python', '-u', '/media/khanh/khanh4/lidar_segmentation/EfficientLPS/tools/train.py', '--local_rank=0', '/media/khanh/khanh4/lidar_segmentation/EfficientLPS/configs/efficientLPS_multigpu_sample.py', '--launcher', 'pytorch', '--work_dir', '../work_dirs/checkpoints', '--validate']' returned non-zero exit status 1.

I don't know how to resolve this issue. Please help me!!
I set the number of GPU = 1.
Thank you.

**Comment by hamin-song** [comment]
I have the same problem as you. Did you solve it?

**Comment by mohan1914** [comment]
RuntimeError: CUDA error: no kernel image is available for execution on the device
This error shows up when the installed torch version is not compatible with the CUDA version on the system.

**Comment by hamin-song** [comment]
@mohan1914 
Thank you for replying!!
Actually, my error looks as follows.
(It has the same subprocess.CalledProcessError, but It has another reason.)

Traceback (most recent call last):
  File "./tools/train.py", line 8, in <module>
    import mmcv
  File "/home/user/anaconda3/envs/efficientLPS/lib/python3.7/site-packages/mmcv/__init__.py", line 8, in <module>
    from .video import *
  File "/home/user/anaconda3/envs/efficientLPS/lib/python3.7/site-packages/mmcv/video/__init__.py", line 3, in <module>
    from .optflow import (dequantize_flow, flow_warp, flowread, flowwrite,
  File "/home/user/anaconda3/envs/efficientLPS/lib/python3.7/site-packages/mmcv/video/optflow.py", line 4, in <module>
    from mmcv._ext import flow_warp_c
  File "mmcv/video/optflow_warp/flow_warp_module.pyx", line 1, in init mmcv._ext
ValueError: numpy.ndarray size changed, may indicate binary incompatibility. Expected 88 from C header, got 80 from PyObject
Traceback (most recent call last):
  File "/home/user/anaconda3/envs/efficientLPS/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/home/user/anaconda3/envs/efficientLPS/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/user/anaconda3/envs/efficientLPS/lib/python3.7/site-packages/torch/distributed/launch.py", line 260, in <module>
    main()
  File "/home/user/anaconda3/envs/efficientLPS/lib/python3.7/site-packages/torch/distributed/launch.py", line 256, in main
    cmd=cmd)
subprocess.CalledProcessError: Command '['/home/user/anaconda3/envs/efficientLPS/bin/python', '-u', './tools/train.py', '--local_rank=0', 'efficientPS_multigpu_sample.py', '--launcher', 'pytorch', '--work_dir', '../work_dirs/checkpoints', '--validate']' returned non-zero exit status 1.

**Comment by tranbaokhanh26** [comment]
Hello Abhinav Valada and Rohit Mohan. When I tried to fix CUDA error, I face this error, can I need to do to fix it. 

ImportError: /media/khanh/khanh4/lidar_segmentation/EfficientLPS/mmdet/ops/dcn/deform_conv_cuda.cpython-37m-x86_64-linux-gnu.so: undefined symbol: _ZN6caffe28TypeMeta21_typeMetaDataInstanceIdEEPKNS_6detail12TypeMetaDataEv
ERROR:torch.distributed.elastic.multiprocessing.api:failed (exitcode: 1) local_rank: 0 (pid: 30874) of binary: /home/khanh/anaconda3/envs/efficientLPS_env/bin/python

=======================
This is all of thing I get when I fix CUDA error.
=======================

/home/khanh/anaconda3/envs/efficientLPS_env/lib/python3.7/site-packages/torch/distributed/launch.py:186: FutureWarning: The module torch.distributed.launch is deprecated
and will be removed in future. Use torchrun.
Note that --use_env is set by default in torchrun.
If your script expects `--local_rank` argument to be set, please
change it to read from `os.environ['LOCAL_RANK']` instead. See 
https://pytorch.org/docs/stable/distributed.html#launch-utility for 
further instructions

  FutureWarning,
Traceback (most recent call last):
  File "/media/khanh/khanh4/lidar_segmentation/EfficientLPS/tools/train.py", line 17, in <module>
    from mmdet.apis import set_random_seed, train_detector
  File "/media/khanh/khanh4/lidar_segmentation/EfficientLPS/mmdet/apis/__init__.py", line 1, in <module>
    from .inference import (async_inference_detector, inference_detector,
  File "/media/khanh/khanh4/lidar_segmentation/EfficientLPS/mmdet/apis/inference.py", line 11, in <module>
    from mmdet.core import get_classes
  File "/media/khanh/khanh4/lidar_segmentation/EfficientLPS/mmdet/core/__init__.py", line 7, in <module>
    from .post_processing import *  # noqa: F401, F403
  File "/media/khanh/khanh4/lidar_segmentation/EfficientLPS/mmdet/core/post_processing/__init__.py", line 1, in <module>
    from .bbox_nms import multiclass_nms
  File "/media/khanh/khanh4/lidar_segmentation/EfficientLPS/mmdet/core/post_processing/bbox_nms.py", line 3, in <module>
    from mmdet.ops.nms import nms_wrapper
  File "/media/khanh/khanh4/lidar_segmentation/EfficientLPS/mmdet/ops/__init__.py", line 2, in <module>
    from .conv import build_conv_layer
  File "/media/khanh/khanh4/lidar_segmentation/EfficientLPS/mmdet/ops/conv.py", line 4, in <module>
    from .dcn import DeformConvPack, ModulatedDeformConvPack
  File "/media/khanh/khanh4/lidar_segmentation/EfficientLPS/mmdet/ops/dcn/__init__.py", line 1, in <module>
    from .deform_conv import (DeformConv, DeformConvPack, ModulatedDeformConv,
  File "/media/khanh/khanh4/lidar_segmentation/EfficientLPS/mmdet/ops/dcn/deform_conv.py", line 11, in <module>
    from . import deform_conv_cuda
ImportError: /media/khanh/khanh4/lidar_segmentation/EfficientLPS/mmdet/ops/dcn/deform_conv_cuda.cpython-37m-x86_64-linux-gnu.so: undefined symbol: _ZN6caffe28TypeMeta21_typeMetaDataInstanceIdEEPKNS_6detail12TypeMetaDataEv
ERROR:torch.distributed.elastic.multiprocessing.api:failed (exitcode: 1) local_rank: 0 (pid: 30874) of binary: /home/khanh/anaconda3/envs/efficientLPS_env/bin/python
Traceback (most recent call last):
  File "/home/khanh/anaconda3/envs/efficientLPS_env/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/home/khanh/anaconda3/envs/efficientLPS_env/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/khanh/anaconda3/envs/efficientLPS_env/lib/python3.7/site-packages/torch/distributed/launch.py", line 193, in <module>
    main()
  File "/home/khanh/anaconda3/envs/efficientLPS_env/lib/python3.7/site-packages/torch/distributed/launch.py", line 189, in main
    launch(args)
  File "/home/khanh/anaconda3/envs/efficientLPS_env/lib/python3.7/site-packages/torch/distributed/launch.py", line 174, in launch
    run(args)
  File "/home/khanh/anaconda3/envs/efficientLPS_env/lib/python3.7/site-packages/torch/distributed/run.py", line 718, in run
    )(*cmd_args)
  File "/home/khanh/anaconda3/envs/efficientLPS_env/lib/python3.7/site-packages/torch/distributed/launcher/api.py", line 131, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
  File "/home/khanh/anaconda3/envs/efficientLPS_env/lib/python3.7/site-packages/torch/distributed/launcher/api.py", line 247, in launch_agent
    failures=result.failures,
torch.distributed.elastic.multiprocessing.errors.ChildFailedError: 
============================================================
/media/khanh/khanh4/lidar_segmentation/EfficientLPS/tools/train.py FAILED
------------------------------------------------------------
Failures:
  <NO_OTHER_FAILURES>
------------------------------------------------------------
Root Cause (first observed failure):
[0]:
  time      : 2022-04-06_11:23:51
  host      : khanh26
  rank      : 0 (local_rank: 0)
  exitcode  : 1 (pid: 30874)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
============================================================

**Comment by tranbaokhanh26** [comment]
Hello Abhinav Valada and Rohit Mohan. When I tried to fix CUDA error, I face this error, can I need to do to fix it.

ImportError: /media/khanh/khanh4/lidar_segmentation/EfficientLPS/mmdet/ops/dcn/deform_conv_cuda.cpython-37m-x86_64-linux-gnu.so: undefined symbol: _ZN6caffe28TypeMeta21_typeMetaDataInstanceIdEEPKNS_6detail12TypeMetaDataEv
ERROR:torch.distributed.elastic.multiprocessing.api:failed (exitcode: 1) local_rank: 0 (pid: 30874) of binary: /home/khanh/anaconda3/envs/efficientLPS_env/bin/python

=======================
This is all of thing I get when I fix CUDA error.
/home/khanh/anaconda3/envs/efficientLPS_env/lib/python3.7/site-packages/torch/distributed/launch.py:186: FutureWarning: The module torch.distributed.launch is deprecated
and will be removed in future. Use torchrun.
Note that --use_env is set by default in torchrun.
If your script expects --local_rank argument to be set, please
change it to read from os.environ['LOCAL_RANK'] instead. See
https://pytorch.org/docs/stable/distributed.html#launch-utility for
further instructions

FutureWarning,
Traceback (most recent call last):
File "/media/khanh/khanh4/lidar_segmentation/EfficientLPS/tools/train.py", line 17, in
from mmdet.apis import set_random_seed, train_detector
File "/media/khanh/khanh4/lidar_segmentation/EfficientLPS/mmdet/apis/init.py", line 1, in
from .inference import (async_inference_detector, inference_detector,
File "/media/khanh/khanh4/lidar_segmentation/EfficientLPS/mmdet/apis/inference.py", line 11, in
from mmdet.core import get_classes
File "/media/khanh/khanh4/lidar_segmentation/EfficientLPS/mmdet/core/init.py", line 7, in
from .post_processing import * # noqa: F401, F403
File "/media/khanh/khanh4/lidar_segmentation/EfficientLPS/mmdet/core/post_processing/init.py", line 1, in
from .bbox_nms import multiclass_nms
File "/media/khanh/khanh4/lidar_segmentation/EfficientLPS/mmdet/core/post_processing/bbox_nms.py", line 3, in
from mmdet.ops.nms import nms_wrapper
File "/media/khanh/khanh4/lidar_segmentation/EfficientLPS/mmdet/ops/init.py", line 2, in
from .conv import build_conv_layer
File "/media/khanh/khanh4/lidar_segmentation/EfficientLPS/mmdet/ops/conv.py", line 4, in
from .dcn import DeformConvPack, ModulatedDeformConvPack
File "/media/khanh/khanh4/lidar_segmentation/EfficientLPS/mmdet/ops/dcn/init.py", line 1, in
from .deform_conv import (DeformConv, DeformConvPack, ModulatedDeformConv,
File "/media/khanh/khanh4/lidar_segmentation/EfficientLPS/mmdet/ops/dcn/deform_conv.py", line 11, in
from . import deform_conv_cuda
ImportError: /media/khanh/khanh4/lidar_segmentation/EfficientLPS/mmdet/ops/dcn/deform_conv_cuda.cpython-37m-x86_64-linux-gnu.so: undefined symbol: _ZN6caffe28TypeMeta21_typeMetaDataInstanceIdEEPKNS_6detail12TypeMetaDataEv
ERROR:torch.distributed.elastic.multiprocessing.api:failed (exitcode: 1) local_rank: 0 (pid: 30874) of binary: /home/khanh/anaconda3/envs/efficientLPS_env/bin/python
Traceback (most recent call last):
File "/home/khanh/anaconda3/envs/efficientLPS_env/lib/python3.7/runpy.py", line 193, in _run_module_as_main
"main", mod_spec)
File "/home/khanh/anaconda3/envs/efficientLPS_env/lib/python3.7/runpy.py", line 85, in _run_code
exec(code, run_globals)
File "/home/khanh/anaconda3/envs/efficientLPS_env/lib/python3.7/site-packages/torch/distributed/launch.py", line 193, in
main()
File "/home/khanh/anaconda3/envs/efficientLPS_env/lib/python3.7/site-packages/torch/distributed/launch.py", line 189, in main
launch(args)
File "/home/khanh/anaconda3/envs/efficientLPS_env/lib/python3.7/site-packages/torch/distributed/launch.py", line 174, in launch
run(args)
File "/home/khanh/anaconda3/envs/efficientLPS_env/lib/python3.7/site-packages/torch/distributed/run.py", line 718, in run
)(*cmd_args)
File "/home/khanh/anaconda3/envs/efficientLPS_env/lib/python3.7/site-packages/torch/distributed/launcher/api.py", line 131, in call
return launch_agent(self._config, self._entrypoint, list(args))
File "/home/khanh/anaconda3/envs/efficientLPS_env/lib/python3.7/site-packages/torch/distributed/launcher/api.py", line 247, in launch_agent
failures=result.failures,
torch.distributed.elastic.multiprocessing.errors.ChildFailedError:
/media/khanh/khanh4/lidar_segmentation/EfficientLPS/tools/train.py FAILED
Failures:
<NO_OTHER_FAILURES>
Root Cause (first observed failure):
[0]:
time : 2022-04-06_11:23:51
host : khanh26
rank : 0 (local_rank: 0)
exitcode : 1 (pid: 30874)
error_file: <N/A>
traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html

**Comment by tranbaokhanh26** [comment]
Hello Abhinav Valada and Rohit Mohan. When I tried to fix CUDA error, I face this error, can I need to do to fix it.

ImportError: /media/khanh/khanh4/lidar_segmentation/EfficientLPS/mmdet/ops/dcn/deform_conv_cuda.cpython-37m-x86_64-linux-gnu.so: undefined symbol: _ZN6caffe28TypeMeta21_typeMetaDataInstanceIdEEPKNS_6detail12TypeMetaDataEv
ERROR:torch.distributed.elastic.multiprocessing.api:failed (exitcode: 1) local_rank: 0 (pid: 30874) of binary: /home/khanh/anaconda3/envs/efficientLPS_env/bin/python

=======================
This is all of thing I get when I fix CUDA error.
=======================

/home/khanh/anaconda3/envs/efficientLPS_env/lib/python3.7/site-packages/torch/distributed/launch.py:186: FutureWarning: The module torch.distributed.launch is deprecated
and will be removed in future. Use torchrun.
Note that --use_env is set by default in torchrun.
If your script expects `--local_rank` argument to be set, please
change it to read from `os.environ['LOCAL_RANK']` instead. See 
https://pytorch.org/docs/stable/distributed.html#launch-utility for 
further instructions

  FutureWarning,
Traceback (most recent call last):
  File "/media/khanh/khanh4/lidar_segmentation/EfficientLPS/tools/train.py", line 17, in <module>
    from mmdet.apis import set_random_seed, train_detector
  File "/media/khanh/khanh4/lidar_segmentation/EfficientLPS/mmdet/apis/__init__.py", line 1, in <module>
    from .inference import (async_inference_detector, inference_detector,
  File "/media/khanh/khanh4/lidar_segmentation/EfficientLPS/mmdet/apis/inference.py", line 11, in <module>
    from mmdet.core import get_classes
  File "/media/khanh/khanh4/lidar_segmentation/EfficientLPS/mmdet/core/__init__.py", line 7, in <module>
    from .post_processing import *  # noqa: F401, F403
  File "/media/khanh/khanh4/lidar_segmentation/EfficientLPS/mmdet/core/post_processing/__init__.py", line 1, in <module>
    from .bbox_nms import multiclass_nms
  File "/media/khanh/khanh4/lidar_segmentation/EfficientLPS/mmdet/core/post_processing/bbox_nms.py", line 3, in <module>
    from mmdet.ops.nms import nms_wrapper
  File "/media/khanh/khanh4/lidar_segmentation/EfficientLPS/mmdet/ops/__init__.py", line 2, in <module>
    from .conv import build_conv_layer
  File "/media/khanh/khanh4/lidar_segmentation/EfficientLPS/mmdet/ops/conv.py", line 4, in <module>
    from .dcn import DeformConvPack, ModulatedDeformConvPack
  File "/media/khanh/khanh4/lidar_segmentation/EfficientLPS/mmdet/ops/dcn/__init__.py", line 1, in <module>
    from .deform_conv import (DeformConv, DeformConvPack, ModulatedDeformConv,
  File "/media/khanh/khanh4/lidar_segmentation/EfficientLPS/mmdet/ops/dcn/deform_conv.py", line 11, in <module>
    from . import deform_conv_cuda
ImportError: /media/khanh/khanh4/lidar_segmentation/EfficientLPS/mmdet/ops/dcn/deform_conv_cuda.cpython-37m-x86_64-linux-gnu.so: undefined symbol: _ZN6caffe28TypeMeta21_typeMetaDataInstanceIdEEPKNS_6detail12TypeMetaDataEv
ERROR:torch.distributed.elastic.multiprocessing.api:failed (exitcode: 1) local_rank: 0 (pid: 30874) of binary: /home/khanh/anaconda3/envs/efficientLPS_env/bin/python
Traceback (most recent call last):
  File "/home/khanh/anaconda3/envs/efficientLPS_env/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/home/khanh/anaconda3/envs/efficientLPS_env/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/khanh/anaconda3/envs/efficientLPS_env/lib/python3.7/site-packages/torch/distributed/launch.py", line 193, in <module>
    main()
  File "/home/khanh/anaconda3/envs/efficientLPS_env/lib/python3.7/site-packages/torch/distributed/launch.py", line 189, in main
    launch(args)
  File "/home/khanh/anaconda3/envs/efficientLPS_env/lib/python3.7/site-packages/torch/distributed/launch.py", line 174, in launch
    run(args)
  File "/home/khanh/anaconda3/envs/efficientLPS_env/lib/python3.7/site-packages/torch/distributed/run.py", line 718, in run
    )(*cmd_args)
  File "/home/khanh/anaconda3/envs/efficientLPS_env/lib/python3.7/site-packages/torch/distributed/launcher/api.py", line 131, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
  File "/home/khanh/anaconda3/envs/efficientLPS_env/lib/python3.7/site-packages/torch/distributed/launcher/api.py", line 247, in launch_agent
    failures=result.failures,
torch.distributed.elastic.multiprocessing.errors.ChildFailedError: 
============================================================
/media/khanh/khanh4/lidar_segmentation/EfficientLPS/tools/train.py FAILED
------------------------------------------------------------
Failures:
  <NO_OTHER_FAILURES>
------------------------------------------------------------
Root Cause (first observed failure):
[0]:
  time      : 2022-04-06_11:23:51
  host      : khanh26
  rank      : 0 (local_rank: 0)
  exitcode  : 1 (pid: 30874)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
============================================================

**Comment by tranbaokhanh26** [comment]
/home/khanh/anaconda3/envs/efficientLPS_env/lib/python3.7/site-packages/torch/distributed/launch.py:186: FutureWarning: The module torch.distributed.launch is deprecated
and will be removed in future. Use torchrun.
Note that --use_env is set by default in torchrun.
If your script expects `--local_rank` argument to be set, please
change it to read from `os.environ['LOCAL_RANK']` instead. See 
https://pytorch.org/docs/stable/distributed.html#launch-utility for 
further instructions

  FutureWarning,
Traceback (most recent call last):
  File "/media/khanh/khanh4/lidar_segmentation/EfficientLPS/tools/train.py", line 17, in <module>
    from mmdet.apis import set_random_seed, train_detector
  File "/media/khanh/khanh4/lidar_segmentation/EfficientLPS/mmdet/apis/__init__.py", line 1, in <module>
    from .inference import (async_inference_detector, inference_detector,
  File "/media/khanh/khanh4/lidar_segmentation/EfficientLPS/mmdet/apis/inference.py", line 11, in <module>
    from mmdet.core import get_classes
  File "/media/khanh/khanh4/lidar_segmentation/EfficientLPS/mmdet/core/__init__.py", line 7, in <module>
    from .post_processing import *  # noqa: F401, F403
  File "/media/khanh/khanh4/lidar_segmentation/EfficientLPS/mmdet/core/post_processing/__init__.py", line 1, in <module>
    from .bbox_nms import multiclass_nms
  File "/media/khanh/khanh4/lidar_segmentation/EfficientLPS/mmdet/core/post_processing/bbox_nms.py", line 3, in <module>
    from mmdet.ops.nms import nms_wrapper
  File "/media/khanh/khanh4/lidar_segmentation/EfficientLPS/mmdet/ops/__init__.py", line 2, in <module>
    from .conv import build_conv_layer
  File "/media/khanh/khanh4/lidar_segmentation/EfficientLPS/mmdet/ops/conv.py", line 4, in <module>
    from .dcn import DeformConvPack, ModulatedDeformConvPack
  File "/media/khanh/khanh4/lidar_segmentation/EfficientLPS/mmdet/ops/dcn/__init__.py", line 1, in <module>
    from .deform_conv import (DeformConv, DeformConvPack, ModulatedDeformConv,
  File "/media/khanh/khanh4/lidar_segmentation/EfficientLPS/mmdet/ops/dcn/deform_conv.py", line 11, in <module>
    from . import deform_conv_cuda
ImportError: /media/khanh/khanh4/lidar_segmentation/EfficientLPS/mmdet/ops/dcn/deform_conv_cuda.cpython-37m-x86_64-linux-gnu.so: undefined symbol: _ZN6caffe28TypeMeta21_typeMetaDataInstanceIdEEPKNS_6detail12TypeMetaDataEv
ERROR:torch.distributed.elastic.multiprocessing.api:failed (exitcode: 1) local_rank: 0 (pid: 30874) of binary: /home/khanh/anaconda3/envs/efficientLPS_env/bin/python
Traceback (most recent call last):
  File "/home/khanh/anaconda3/envs/efficientLPS_env/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/home/khanh/anaconda3/envs/efficientLPS_env/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/khanh/anaconda3/envs/efficientLPS_env/lib/python3.7/site-packages/torch/distributed/launch.py", line 193, in <module>
    main()
  File "/home/khanh/anaconda3/envs/efficientLPS_env/lib/python3.7/site-packages/torch/distributed/launch.py", line 189, in main
    launch(args)
  File "/home/khanh/anaconda3/envs/efficientLPS_env/lib/python3.7/site-packages/torch/distributed/launch.py", line 174, in launch
    run(args)
  File "/home/khanh/anaconda3/envs/efficientLPS_env/lib/python3.7/site-packages/torch/distributed/run.py", line 718, in run
    )(*cmd_args)
  File "/home/khanh/anaconda3/envs/efficientLPS_env/lib/python3.7/site-packages/torch/distributed/launcher/api.py", line 131, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
  File "/home/khanh/anaconda3/envs/efficientLPS_env/lib/python3.7/site-packages/torch/distributed/launcher/api.py", line 247, in launch_agent
    failures=result.failures,
torch.distributed.elastic.multiprocessing.errors.ChildFailedError: 
============================================================
/media/khanh/khanh4/lidar_segmentation/EfficientLPS/tools/train.py FAILED
------------------------------------------------------------
Failures:
  <NO_OTHER_FAILURES>
------------------------------------------------------------
Root Cause (first observed failure):
[0]:
  time      : 2022-04-06_11:23:51
  host      : khanh26
  rank      : 0 (local_rank: 0)
  exitcode  : 1 (pid: 30874)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
============================================================

**Comment by tranbaokhanh26** [comment]
Hello Abhinav Valada and Rohit Mohan, when I tried to fix CUDA error, I get another problem. Can I ask the way to resolve it?

/home/khanh/anaconda3/envs/efficientLPS_env/lib/python3.7/site-packages/torch/distributed/launch.py:186: FutureWarning: The module torch.distributed.launch is deprecated
and will be removed in future. Use torchrun.
Note that --use_env is set by default in torchrun.
If your script expects `--local_rank` argument to be set, please
change it to read from `os.environ['LOCAL_RANK']` instead. See 
https://pytorch.org/docs/stable/distributed.html#launch-utility for 
further instructions

  FutureWarning,
Traceback (most recent call last):
  File "/media/khanh/khanh4/lidar_segmentation/EfficientLPS/tools/train.py", line 17, in <module>
    from mmdet.apis import set_random_seed, train_detector
  File "/media/khanh/khanh4/lidar_segmentation/EfficientLPS/mmdet/apis/__init__.py", line 1, in <module>
    from .inference import (async_inference_detector, inference_detector,
  File "/media/khanh/khanh4/lidar_segmentation/EfficientLPS/mmdet/apis/inference.py", line 11, in <module>
    from mmdet.core import get_classes
  File "/media/khanh/khanh4/lidar_segmentation/EfficientLPS/mmdet/core/__init__.py", line 7, in <module>
    from .post_processing import *  # noqa: F401, F403
  File "/media/khanh/khanh4/lidar_segmentation/EfficientLPS/mmdet/core/post_processing/__init__.py", line 1, in <module>
    from .bbox_nms import multiclass_nms
  File "/media/khanh/khanh4/lidar_segmentation/EfficientLPS/mmdet/core/post_processing/bbox_nms.py", line 3, in <module>
    from mmdet.ops.nms import nms_wrapper
  File "/media/khanh/khanh4/lidar_segmentation/EfficientLPS/mmdet/ops/__init__.py", line 2, in <module>
    from .conv import build_conv_layer
  File "/media/khanh/khanh4/lidar_segmentation/EfficientLPS/mmdet/ops/conv.py", line 4, in <module>
    from .dcn import DeformConvPack, ModulatedDeformConvPack
  File "/media/khanh/khanh4/lidar_segmentation/EfficientLPS/mmdet/ops/dcn/__init__.py", line 1, in <module>
    from .deform_conv import (DeformConv, DeformConvPack, ModulatedDeformConv,
  File "/media/khanh/khanh4/lidar_segmentation/EfficientLPS/mmdet/ops/dcn/deform_conv.py", line 11, in <module>
    from . import deform_conv_cuda
ImportError: /media/khanh/khanh4/lidar_segmentation/EfficientLPS/mmdet/ops/dcn/deform_conv_cuda.cpython-37m-x86_64-linux-gnu.so: undefined symbol: _ZN6caffe28TypeMeta21_typeMetaDataInstanceIdEEPKNS_6detail12TypeMetaDataEv
ERROR:torch.distributed.elastic.multiprocessing.api:failed (exitcode: 1) local_rank: 0 (pid: 4060) of binary: /home/khanh/anaconda3/envs/efficientLPS_env/bin/python
Traceback (most recent call last):
  File "/home/khanh/anaconda3/envs/efficientLPS_env/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/home/khanh/anaconda3/envs/efficientLPS_env/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/khanh/anaconda3/envs/efficientLPS_env/lib/python3.7/site-packages/torch/distributed/launch.py", line 193, in <module>
    main()
  File "/home/khanh/anaconda3/envs/efficientLPS_env/lib/python3.7/site-packages/torch/distributed/launch.py", line 189, in main
    launch(args)
  File "/home/khanh/anaconda3/envs/efficientLPS_env/lib/python3.7/site-packages/torch/distributed/launch.py", line 174, in launch
    run(args)
  File "/home/khanh/anaconda3/envs/efficientLPS_env/lib/python3.7/site-packages/torch/distributed/run.py", line 718, in run
    )(*cmd_args)
  File "/home/khanh/anaconda3/envs/efficientLPS_env/lib/python3.7/site-packages/torch/distributed/launcher/api.py", line 131, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
  File "/home/khanh/anaconda3/envs/efficientLPS_env/lib/python3.7/site-packages/torch/distributed/launcher/api.py", line 247, in launch_agent
    failures=result.failures,
torch.distributed.elastic.multiprocessing.errors.ChildFailedError:

**Comment by mohan1914** [comment]
I think there were some build files still there from your last compilation. You should do a fresh install and see if the error persists.
